name: "Terraform ECS provisioning"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
        
# comment out because testing in poc env, once ready to test in dev or other envs, enable them
#  push:
#    branches: [ main ]
#    paths: 'terraform/**'
#  pull_request:
#    branches: [ main ]
#    paths: 'terraform/**'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  infracost:
    permissions:
      contents: write
      pull-requests: write
    uses: wenqiglantz/reusable-workflows-modules/.github/workflows/terraform-infracost.yml@main
    with:
      # need to specify working-directory as that's where the terraform files live in the source code
      working-directory: ./terraform
      terraform-var-file: ./.env/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
      usage-file: ./.env/${{ github.event.inputs.environment || 'dev' }}/infracost-usage.yml
      infracost-flag: true # flag whether or not to run infracost analysis
    secrets: inherit

  terraform:
    needs: infracost
    permissions:
      id-token: write  # need this for OIDC
      contents: read   
    uses: wenqiglantz/reusable-workflows-modules/.github/workflows/terraform.yml@main
    with:
      # need to specify working-directory as that's where the terraform files live in the source code
      working-directory: ./terraform
    secrets: inherit
